default_provider: openai
default_agent: chat
providers:
  openai:
    model: openai/gpt-5
    reasoning_effort: "minimal"
    base_url: https://api.openai.com/v1
    api_key: ${OPENAI_API_KEY}
agents: !include "agents/*.yml"
